import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1719933089676 implements MigrationInterface {
    name = 'Migration1719933089676'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_created_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_updated_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" DROP CONSTRAINT "application_news_program_id_links_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" DROP CONSTRAINT "application_news_program_id_links_inv_fk"`);
        await queryRunner.query(`ALTER TABLE "up_users" DROP CONSTRAINT "up_users_created_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "up_users" DROP CONSTRAINT "up_users_updated_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" DROP CONSTRAINT "application_news_user_id_links_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" DROP CONSTRAINT "application_news_user_id_links_inv_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news" DROP CONSTRAINT "application_news_created_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news" DROP CONSTRAINT "application_news_updated_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP CONSTRAINT "application_news_information_id_links_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP CONSTRAINT "application_news_information_id_links_inv_fk"`);
        await queryRunner.query(`ALTER TABLE "information" DROP CONSTRAINT "information_created_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "information" DROP CONSTRAINT "information_updated_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" DROP CONSTRAINT "information_user_id_links_fk"`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" DROP CONSTRAINT "information_user_id_links_inv_fk"`);
        await queryRunner.query(`ALTER TABLE "cycles" DROP CONSTRAINT "cycles_created_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "cycles" DROP CONSTRAINT "cycles_updated_by_id_fk"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" DROP CONSTRAINT "cycles_program_links_fk"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" DROP CONSTRAINT "cycles_program_links_inv_fk"`);
        await queryRunner.query(`DROP INDEX "public"."application_news_information_id_links_order_inv_fk"`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" DROP CONSTRAINT "application_news_program_id_links_unique"`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" DROP CONSTRAINT "application_news_user_id_links_unique"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP CONSTRAINT "application_news_information_id_links_unique"`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" DROP CONSTRAINT "information_user_id_links_unique"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" DROP CONSTRAINT "cycles_program_links_unique"`);
        await queryRunner.query(`CREATE TABLE "student" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "interviewDate" character varying NOT NULL, CONSTRAINT "PK_3d8016e1cb58429474a3c041904" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz" ("id" SERIAL NOT NULL, "codeRate" double precision NOT NULL, "logicRate" double precision NOT NULL, "theoreticalRate" double precision NOT NULL, "codeScore" double precision NOT NULL, "logicScore" double precision NOT NULL, "theoreticalScore" double precision NOT NULL, "totalScore" double precision NOT NULL, "comments" character varying NOT NULL DEFAULT '', "pace" double precision NOT NULL, "studentId" integer NOT NULL, CONSTRAINT "REL_5b58c9c1f6f672157e28cf6495" UNIQUE ("studentId"), CONSTRAINT "PK_422d974e7217414e029b3e641d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question" ("id" SERIAL NOT NULL, "question" character varying NOT NULL, "answer" character varying NOT NULL, "difficulty" character varying NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quiz_questions" ("quizId" integer NOT NULL, "questionId" integer NOT NULL, "answer" character varying NOT NULL, "correct" boolean NOT NULL, "rating" integer NOT NULL, CONSTRAINT "PK_041c7884328e13eba070ccd9883" PRIMARY KEY ("quizId", "questionId"))`);
        await queryRunner.query(`CREATE TABLE "panel_admins" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL, "updated_at" TIMESTAMP NOT NULL, "isActive" boolean NOT NULL, "reset_token" character varying, "reset_token_expiry" TIMESTAMP, "login_attempts" integer NOT NULL, CONSTRAINT "UQ_a76b4e11ce270b546b5d3823ca7" UNIQUE ("email"), CONSTRAINT "PK_3e165a641639aa994b937e91dc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "cycles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "cycles" ADD "cycle_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "program_name"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "program_name" character varying`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "abbreviation"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "abbreviation" character varying`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "curriculum_url"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "curriculum_url" character varying`);
        await queryRunner.query(`ALTER TABLE "programs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "programs" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ALTER COLUMN "application_new_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ALTER COLUMN "program_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ALTER COLUMN "application_new_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ALTER COLUMN "application_new_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ALTER COLUMN "info_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP COLUMN "application_new_order"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD "application_new_order" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ALTER COLUMN "info_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "from_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "to_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ALTER COLUMN "cycle_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ADD CONSTRAINT "UQ_45d73655f5824c1108368a94e3e" UNIQUE ("cycle_id")`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ALTER COLUMN "program_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ADD CONSTRAINT "FK_298b0a59268ee00ab2b648330e2" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ADD CONSTRAINT "FK_e6ad7b0515212a95554f5cd68bd" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ADD CONSTRAINT "FK_2f74eddd96ec105d369b4f3edd4" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ADD CONSTRAINT "FK_cdc177df969dadcd47167e9ebdb" FOREIGN KEY ("user_id") REFERENCES "up_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD CONSTRAINT "FK_603b1043d111dd9e0b35f696893" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD CONSTRAINT "FK_77be8094eb3a19d94a177a35399" FOREIGN KEY ("info_id") REFERENCES "information"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ADD CONSTRAINT "FK_3fff4d14c2024d8784b8f0963db" FOREIGN KEY ("info_id") REFERENCES "information"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ADD CONSTRAINT "FK_65ecd241d8f775fc088cf5be372" FOREIGN KEY ("user_id") REFERENCES "up_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quiz" ADD CONSTRAINT "FK_5b58c9c1f6f672157e28cf6495e" FOREIGN KEY ("studentId") REFERENCES "student"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD CONSTRAINT "FK_8889ccc5a40989ea308a588870e" FOREIGN KEY ("quizId") REFERENCES "quiz"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD CONSTRAINT "FK_2deb89a4271b6f0e1aa30c2b07a" FOREIGN KEY ("questionId") REFERENCES "question"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ADD CONSTRAINT "FK_45d73655f5824c1108368a94e3e" FOREIGN KEY ("cycle_id") REFERENCES "cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cycles_program_links" DROP CONSTRAINT "FK_45d73655f5824c1108368a94e3e"`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP CONSTRAINT "FK_2deb89a4271b6f0e1aa30c2b07a"`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP CONSTRAINT "FK_8889ccc5a40989ea308a588870e"`);
        await queryRunner.query(`ALTER TABLE "quiz" DROP CONSTRAINT "FK_5b58c9c1f6f672157e28cf6495e"`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" DROP CONSTRAINT "FK_65ecd241d8f775fc088cf5be372"`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" DROP CONSTRAINT "FK_3fff4d14c2024d8784b8f0963db"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP CONSTRAINT "FK_77be8094eb3a19d94a177a35399"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP CONSTRAINT "FK_603b1043d111dd9e0b35f696893"`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" DROP CONSTRAINT "FK_cdc177df969dadcd47167e9ebdb"`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" DROP CONSTRAINT "FK_2f74eddd96ec105d369b4f3edd4"`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" DROP CONSTRAINT "FK_e6ad7b0515212a95554f5cd68bd"`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" DROP CONSTRAINT "FK_298b0a59268ee00ab2b648330e2"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ALTER COLUMN "program_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" DROP CONSTRAINT "UQ_45d73655f5824c1108368a94e3e"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ALTER COLUMN "cycle_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "updated_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "created_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "to_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cycles" ALTER COLUMN "from_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ALTER COLUMN "info_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" DROP COLUMN "application_new_order"`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD "application_new_order" double precision`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ALTER COLUMN "info_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ALTER COLUMN "application_new_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ALTER COLUMN "application_new_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ALTER COLUMN "program_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ALTER COLUMN "application_new_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "programs" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "programs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "curriculum_url"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "curriculum_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "abbreviation"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "abbreviation" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "programs" DROP COLUMN "program_name"`);
        await queryRunner.query(`ALTER TABLE "programs" ADD "program_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cycles" DROP COLUMN "cycle_name"`);
        await queryRunner.query(`ALTER TABLE "cycles" ADD "name" character varying(255)`);
        await queryRunner.query(`DROP TABLE "panel_admins"`);
        await queryRunner.query(`DROP TABLE "quiz_questions"`);
        await queryRunner.query(`DROP TABLE "question"`);
        await queryRunner.query(`DROP TABLE "quiz"`);
        await queryRunner.query(`DROP TABLE "student"`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ADD CONSTRAINT "cycles_program_links_unique" UNIQUE ("cycle_id", "program_id")`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ADD CONSTRAINT "information_user_id_links_unique" UNIQUE ("info_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD CONSTRAINT "application_news_information_id_links_unique" UNIQUE ("application_new_id", "info_id")`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ADD CONSTRAINT "application_news_user_id_links_unique" UNIQUE ("application_new_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ADD CONSTRAINT "application_news_program_id_links_unique" UNIQUE ("application_new_id", "program_id")`);
        await queryRunner.query(`CREATE INDEX "application_news_information_id_links_order_inv_fk" ON "application_news_information_id_links" ("application_new_order") `);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ADD CONSTRAINT "cycles_program_links_inv_fk" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cycles_program_links" ADD CONSTRAINT "cycles_program_links_fk" FOREIGN KEY ("cycle_id") REFERENCES "cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cycles" ADD CONSTRAINT "cycles_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cycles" ADD CONSTRAINT "cycles_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ADD CONSTRAINT "information_user_id_links_inv_fk" FOREIGN KEY ("user_id") REFERENCES "up_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information_user_id_links" ADD CONSTRAINT "information_user_id_links_fk" FOREIGN KEY ("info_id") REFERENCES "information"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information" ADD CONSTRAINT "information_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "information" ADD CONSTRAINT "information_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD CONSTRAINT "application_news_information_id_links_inv_fk" FOREIGN KEY ("info_id") REFERENCES "information"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_information_id_links" ADD CONSTRAINT "application_news_information_id_links_fk" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news" ADD CONSTRAINT "application_news_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news" ADD CONSTRAINT "application_news_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ADD CONSTRAINT "application_news_user_id_links_inv_fk" FOREIGN KEY ("user_id") REFERENCES "up_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_user_id_links" ADD CONSTRAINT "application_news_user_id_links_fk" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "up_users" ADD CONSTRAINT "up_users_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "up_users" ADD CONSTRAINT "up_users_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ADD CONSTRAINT "application_news_program_id_links_inv_fk" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_news_program_id_links" ADD CONSTRAINT "application_news_program_id_links_fk" FOREIGN KEY ("application_new_id") REFERENCES "application_news"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
